/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ViewModel.CH_VMD;
import Service.ICHservice;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP probook
 */
public class QLCH extends javax.swing.JFrame {

    /**
     * Creates new form QLCH
     */
    public QLCH() {
        initComponents();
        tableModel = (DefaultTableModel) tblCH.getModel();
        listCH = service.getListCH();

        setLocationRelativeTo(null);
    }
    DefaultTableModel tableModel = new DefaultTableModel();
    List<CH_VMD> listCH = new ArrayList<>();

    List<CH_VMD> listCH1 = new ArrayList<>();

    ICHservice service = new ICHservice();

    public void Fill() {
        tableModel = (DefaultTableModel) tblCH.getModel();
        listCH = service.getListCH();
        tableModel.setRowCount(0);
        for (CH_VMD ch : listCH) {
            tableModel.addRow(new Object[]{ch.getMa(), ch.getTen(),
                ch.getDiaChi(), ch.getThanhPho(), ch.getQuocGia(),
                ch.getDiaChi() + " " + ch.getThanhPho() + " " + ch.getQuocGia()});

        }
    }

    public boolean check() {
        if (txtMa.getText().isBlank()==true) {
            lblMa.setText("Chống");

        } else {
            lblMa.setText("");
        }
        if (txtTenCH.getText().isBlank()==true) {
            lblten.setText("Chống");
        } else {
            lblten.setText("");
        }
        if (txtDC.getText().isBlank()==true) {
            lblDC.setText("Chống");
        } else {
            lblDC.setText("");
        }
        if (txtTP.getText().isBlank()==true) {
            lblTP.setText("Chống");
        } else {
            lblTP.setText("");
        }
        if (!txtQG.getText().isBlank()==true) {
            lblQG.setText("");
        } else {
            lblQG.setText("Chống");
            return false;
        }

        return true;

    }
    

    public boolean checkMa() {
        for (CH_VMD ch : listCH) {
            if (ch.getMa().equalsIgnoreCase(txtMa.getText())) {
                lblMa.setText("Trùng mã");
                return false;
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCH = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtQG = new javax.swing.JTextField();
        txtTenCH = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        txtDC = new javax.swing.JTextField();
        txtTP = new javax.swing.JTextField();
        btnHienThi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        txtTimdc = new javax.swing.JTextField();
        lblMa = new javax.swing.JLabel();
        lblten = new javax.swing.JLabel();
        lblDC = new javax.swing.JLabel();
        lblTP = new javax.swing.JLabel();
        lblQG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên CH", "Địa chỉ", "Thành phố", "Quốc gia", "DC đầy đủ"
            }
        ));
        tblCH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCH);

        jLabel1.setText("Mã");

        jLabel2.setText("Tên CH");

        jLabel3.setText("Địa chỉ");

        jLabel4.setText("Thành phố");

        jLabel5.setText("Quốc gia");

        btnHienThi.setText("Hiển thị");
        btnHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        lblMa.setText("*");

        lblten.setText("*");

        lblDC.setText("*");

        lblTP.setText("*");

        lblQG.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDC, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTenCH, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(69, 69, 69)
                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQG)
                            .addComponent(lblTP))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTimdc)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblten)
                            .addComponent(lblDC)
                            .addComponent(lblMa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnHienThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(131, 131, 131)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(203, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHienThi)
                    .addComponent(lblMa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem)
                    .addComponent(lblten))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa)
                    .addComponent(lblDC))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim)
                    .addComponent(lblTP))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTimdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(176, 176, 176)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(507, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCHMouseClicked
        // TODO add your handling code here:
        int i = tblCH.getSelectedRow();
        txtMa.setText(tblCH.getValueAt(i, 0).toString());
        txtTenCH.setText(tblCH.getValueAt(i, 1).toString());
        txtDC.setText(tblCH.getValueAt(i, 2).toString());
        txtTP.setText(tblCH.getValueAt(i, 3).toString());
        txtQG.setText(tblCH.getValueAt(i, 4).toString());


    }//GEN-LAST:event_tblCHMouseClicked

    private void btnHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiActionPerformed
        // TODO add your handling code here:
        Fill();
    }//GEN-LAST:event_btnHienThiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
//        CH_VMD c = new CH_VMD();
//        c.setMa(txtMa.getText());
//        c.setTen(txtTenCH.getText());
//        c.setDiaChi(txtDC.getText());
//        c.setThanhPho(txtTP.getText());
//        c.setQuocGia(txtQG.getText());
//        service.themCH(c);
//        JOptionPane.showMessageDialog(this,"Thêm thành công");
//        Fill();
        if (check()) {
            if (checkMa()) {
                CH_VMD c = new CH_VMD();
                c.setMa(txtMa.getText());
                c.setTen(txtTenCH.getText());
                c.setDiaChi(txtDC.getText());
                c.setThanhPho(txtTP.getText());
                c.setQuocGia(txtQG.getText());
                service.themCH(c);
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                Fill();
            }
        }


    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int in = tblCH.getSelectedRow();
        int j = tblCH.getSelectedRowCount()-1 ;
        
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            if (in >= 0) {
                for (int i = in; i <= in + j; i++) {
                    service.xoaCH(tblCH.getValueAt(in, 0).toString());
                    Fill();
                }
                JOptionPane.showMessageDialog(this, "Xóa thành công");

            } else {
                JOptionPane.showMessageDialog(this, "Mời chọn cửa hàng cần xóa");
            }
        } else {
            return;
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
//        tableModel.setRowCount(0);
//        tableModel = (DefaultTableModel) tblCH.getModel();
//        listCH = service.getListCH();
//        for (CH_VMD ch : listCH) {
//            if (txtTimdc.getText().equalsIgnoreCase(ch.getDiaChi())) {
//                tableModel.addRow(new Object[]{ch.getMa(), ch.getTen(),
//                    ch.getDiaChi(), ch.getThanhPho(), ch.getQuocGia(),
//                    ch.getDiaChi() + " " + ch.getThanhPho() + " " + ch.getQuocGia()});
//            }
//
//        }

        tableModel.setRowCount(0);
        tableModel = (DefaultTableModel) tblCH.getModel();
        listCH1 = service.getListCH2(txtTimdc.getText());

        for (CH_VMD ch : listCH1) {
            tableModel.addRow(new Object[]{ch.getMa(), ch.getTen(),
                ch.getDiaChi(), ch.getThanhPho(), ch.getQuocGia(),
                ch.getDiaChi() + " " + ch.getThanhPho() + " " + ch.getQuocGia()});

        }
    }//GEN-LAST:event_btnTimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLCH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHienThi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblDC;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblQG;
    private javax.swing.JLabel lblTP;
    private javax.swing.JLabel lblten;
    private javax.swing.JTable tblCH;
    private javax.swing.JTextField txtDC;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtQG;
    private javax.swing.JTextField txtTP;
    private javax.swing.JTextField txtTenCH;
    private javax.swing.JTextField txtTimdc;
    // End of variables declaration//GEN-END:variables
}
